name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 2.0.9+221

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: any 
  flutter_facebook_auth: 
  google_sign_in: any
  get: ^4.6.5
  provider:
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  flutter_local_notifications: #^13.0.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  intl:
  the_apple_sign_in :
  pin_code_fields: ^7.3.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  flutter_typeahead: #^4.3.1 #^4.0.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  universal_html: ^2.0.8
  universal_ui: #^0.0.8
  flutter_inappwebview: ^5.4.3+8
  flutter_widget_from_html_core: #^0.10.0
  url_launcher: ^6.0.17
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  # phone_number: ^0.12.0+1
  country_code_picker: ^3.0.0
  #country_code_picker: ^3.0.0
  cached_network_image: #^3.2.1
  lottie: #^2.2.0

  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2
  share_plus: #^6.3.1
  custom_map_markers: ^0.0.2+1
  image_compression_flutter: ^1.0.2
  fwfh_text_style: #^2.22.8+1
  flutter_smart_dialog: #^4.9.0+3
  libphonenumber_plugin: #^0.3.1
  smooth_page_indicator: ^1.0.1
  country_codes: ^2.2.0
  country_picker: #^2.0.20
  modal_bottom_sheet: #^2.1.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  web: true
  android: true
  ios: false
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: 'assets/image/ic_launcher-playstore.png'
  image_path: 'assets/image/ic_launcher-playstore.png'

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/lottie/
    - assets/image/weather/day/
    - assets/image/weather/night/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
