// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWfme3FulpbRxcMzQ9JOaRUJPWIn2vKo',
    appId: '1:391440289487:web:20e496a065e0c4c03e31ba',
    messagingSenderId: '391440289487',
    projectId: 'the-africanbasket-351412',
    authDomain: 'the-africanbasket-351412.firebaseapp.com',
    databaseURL: 'https://the-africanbasket-351412-default-rtdb.firebaseio.com',
    storageBucket: 'the-africanbasket-351412.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBs-d3KUt9WDSaZqqQ1wDEwSv-5EfkzIw',
    appId: '1:391440289487:android:5bbdbdbb253b63d73e31ba',
    messagingSenderId: '391440289487',
    projectId: 'the-africanbasket-351412',
    databaseURL: 'https://the-africanbasket-351412-default-rtdb.firebaseio.com',
    storageBucket: 'the-africanbasket-351412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8bgUCUO2EnG19gJ_q-hPTEr7FWKm2Eg',
    appId: '1:391440289487:ios:67346a73b6e7a29f3e31ba',
    messagingSenderId: '391440289487',
    projectId: 'the-africanbasket-351412',
    databaseURL: 'https://the-africanbasket-351412-default-rtdb.firebaseio.com',
    storageBucket: 'the-africanbasket-351412.appspot.com',
    androidClientId: '391440289487-khb7765b1irh449gj8f0ri4iugs04vcq.apps.googleusercontent.com',
    iosClientId: '391440289487-oem6cjgo0bl30rj1ijv6apiiqkvrs7s5.apps.googleusercontent.com',
    iosBundleId: 'com.theafricanbasket.rn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh8bgUCUO2EnG19gJ_q-hPTEr7FWKm2Eg',
    appId: '1:391440289487:ios:68dbf345fcc0fece3e31ba',
    messagingSenderId: '391440289487',
    projectId: 'the-africanbasket-351412',
    databaseURL: 'https://the-africanbasket-351412-default-rtdb.firebaseio.com',
    storageBucket: 'the-africanbasket-351412.appspot.com',
    androidClientId: '391440289487-khb7765b1irh449gj8f0ri4iugs04vcq.apps.googleusercontent.com',
    iosClientId: '391440289487-ds6i7i7an0kcv9vk2d23g48cbrlb8sgv.apps.googleusercontent.com',
    iosBundleId: 'com.theAfricanbasket',
  );
}
